AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Guide Backend - Full Stack

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS,GET,DELETE,PUT,PATCH'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-User-Id'"
      AllowOrigin: "'*'"
    Auth:
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn
          IdentitySource: "method.request.header.Authorization"

Resources:
  ##############################
  # DATA LAYER
  ##############################
  ArticleImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: ["GET", "PUT", "POST", "DELETE", "HEAD"]
            AllowedOrigins: ["*"]
            AllowedHeaders: ["*"]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: articleId
          AttributeType: S
        - AttributeName: visibility
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: ownerId
          AttributeType: S
      KeySchema:
        - AttributeName: articleId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_visibility_createdAt
          KeySchema:
            - AttributeName: visibility
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi_owner_createdAt
          KeySchema:
            - AttributeName: ownerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ##############################
  # AUTH (COGNITO)
  ##############################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: TravelGuideUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: web-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH


  
  ##############################
  # AUTH FUNCTIONS
  ##############################
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: login.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
                - cognito-idp:AdminInitiateAuth
              Resource: !GetAtt UserPool.Arn
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: register.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
              Resource: !GetAtt UserPool.Arn
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: POST

  ConfirmUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: confirm_user.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ConfirmSignUp
              Resource: !GetAtt UserPool.Arn
      Events:
        ConfirmApi:
          Type: Api
          Properties:
            Path: /auth/confirm
            Method: POST

  ##############################
  # ARTICLE FUNCTIONS
  ##############################
  CreateArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: create_article.lambda_handler
      Runtime: python3.11
      Timeout: 20
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticlesTable
          BUCKET_NAME: !Ref ArticleImagesBucket
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArticleImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        CreateArticleApi:
          Type: Api
          Properties:
            Path: /articles
            Method: POST
            Auth:
             Authorizer: CognitoAuthorizer


  GetArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: get_article.lambda_handler
      Runtime: python3.11
      Timeout: 15
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticlesTable
          BUCKET_NAME: !Ref ArticleImagesBucket
          RETURN_403_ON_PRIVATE: "false"
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
        - S3ReadPolicy:
            BucketName: !Ref ArticleImagesBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        GetArticleApi:
          Type: Api
          Properties:
            Path: /articles/{articleId}
            Method: GET

  ListArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: list_articles.lambda_handler
      Runtime: python3.11
      Timeout: 15
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticlesTable
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        ListArticlesApi:
          Type: Api
          Properties:
            Path: /articles
            Method: GET

  UpdateArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: update_article.lambda_handler
      Runtime: python3.11
      Timeout: 20
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticlesTable
          BUCKET_NAME: !Ref ArticleImagesBucket
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArticleImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        UpdateArticleApi:
          Type: Api
          Properties:
            Path: /articles/{articleId}
            Method: PATCH

  DeleteArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: delete_article.lambda_handler
      Runtime: python3.11
      Timeout: 15
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticlesTable
          BUCKET_NAME: !Ref ArticleImagesBucket
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArticleImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        DeleteArticleApi:
          Type: Api
          Properties:
            Path: /articles/{articleId}
            Method: DELETE
            Auth:
             Authorizer: CognitoAuthorizer

  SearchArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: search_articles.lambda_handler
      Runtime: python3.11
      Timeout: 15
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticlesTable
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        SearchArticlesApi:
          Type: Api
          Properties:
            Path: /search
            Method: GET

  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: get_upload_url.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref ArticleImagesBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ArticleImagesBucket
      Events:
        GetUploadUrlApi:
          Type: Api
          Properties:
            Path: /upload-url
            Method: POST

  ##############################
  # THUMBNAIL GENERATOR (S3 trigger)
  ##############################
  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/thumbnail_generator/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 1024
      Environment:
        Variables:
          BUCKET_NAME: !Ref ArticleImagesBucket
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "${ArticleImagesBucket.Arn}/*"
            - Effect: Allow
              Action: s3:ListBucket
              Resource: !GetAtt ArticleImagesBucket.Arn
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

  ##############################
  # STATIC SITE + CLOUDFRONT (OAI)
  ##############################
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AWS::StackName}"

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAIReadOnly
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

  ArticleImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArticleImagesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAIReadImages
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${ArticleImagesBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3OriginStatic
            DomainName: !GetAtt StaticSiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"

          - Id: S3OriginImages
            DomainName: !GetAtt ArticleImagesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"

        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3OriginStatic
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true

        CacheBehaviors:
          - PathPattern: "articles/*"
            TargetOriginId: S3OriginImages
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true

          - PathPattern: "thumbnails/*"
            TargetOriginId: S3OriginImages
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true

        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true
        
Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  ArticleImagesBucketName:
    Value: !Ref ArticleImagesBucket
  StaticSiteBucketName:
    Value: !Ref StaticSiteBucket
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
  CloudFrontDomainForImages:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: Use this domain for serving images via CloudFront for better performance