AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Guide Backend - Full Stack (Fixed CORS + CloudFront + Cognito)

Globals:
  Function:
    Timeout: 20
    Runtime: python3.11
    MemorySize: 512
    Environment:
      Variables:
        # Tự động lấy domain CloudFront thật – không hardcode
        CORS_ORIGIN: !Sub "https://${CloudFrontDistribution.DomainName}"
  
  Api:
    # Giữ lại để API Gateway tự handle OPTIONS (có tác dụng với route không có Authorizer)
    Cors:
      AllowOrigin: !Sub "'https://${CloudFrontDistribution.DomainName}'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,X-User-Id'"
      AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
      AllowCredentials: true
      MaxAge: "'600'"
    Auth:
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn
          IdentitySource: "method.request.header.Authorization"

Resources:
  # ============================== DATA LAYER ==============================
  ArticleImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ["*"]
            AllowedHeaders: ["*"]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: articleId
          AttributeType: S
        - AttributeName: visibility
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: ownerId
          AttributeType: S
      KeySchema:
        - AttributeName: articleId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_visibility_createdAt
          KeySchema:
            - AttributeName: visibility
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi_owner_createdAt
          KeySchema:
            - AttributeName: ownerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ============================== COGNITO ==============================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: TravelGuideUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: web-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH


  # ============================== AUTH FUNCTIONS ==============================
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: login.lambda_handler
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - AmazonCognitoPowerUser
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: register.lambda_handler
      Policies:
        - AmazonCognitoPowerUser
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/register
            Method: POST

  ConfirmUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: confirm_user.lambda_handler
      Policies:
        - AmazonCognitoPowerUser
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/confirm
            Method: POST

  # ============================== ARTICLE FUNCTIONS ==============================
  CreateArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: create_article.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArticleImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - AmazonCognitoReadOnly
      Events:
        Api:
          Type: Api
          Properties:
            Path: /articles
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GetArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: get_article.lambda_handler
      Environment:
        Variables:
          RETURN_403_ON_PRIVATE: "false"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
        - S3ReadPolicy:
            BucketName: !Ref ArticleImagesBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /articles/{articleId}
            Method: GET

  ListArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: list_articles.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /articles
            Method: GET

  UpdateArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: update_article.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArticleImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /articles/{articleId}
            Method: PATCH
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: delete_article.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArticleImagesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /articles/{articleId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

  SearchArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: search_articles.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /search
            Method: GET

  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/articles/
      Handler: get_upload_url.lambda_handler
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ArticleImagesBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /upload-url
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
  # ============================== THUMBNAIL ==============================

  # ThumbnailFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/thumbnail_generator/
  #     Handler: app.lambda_handler
  #     Runtime: python3.11
  #     Timeout: 30
  #     MemorySize: 1024
  #     Environment:
  #       Variables:
  #         BUCKET_NAME: !Ref ArticleImagesBucket
  #     Policies:
  #       - Version: "2012-10-17"
  #         Statement:
  #           - Effect: Allow
  #             Action: [s3:GetObject, s3:PutObject]
  #             Resource: !Sub "${ArticleImagesBucket.Arn}/*"
  #           - Effect: Allow
  #             Action: s3:ListBucket
  #             Resource: !GetAtt ArticleImagesBucket.Arn

  # # PHÁ VÒNG LẶP: Tách ra
  # ThumbnailFunctionBucketEventPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Ref ThumbnailFunction
  #     Action: lambda:InvokeFunction
  #     Principal: s3.amazonaws.com
  #     SourceAccount: !Ref AWS::AccountId
  #     SourceArn: !GetAtt ArticleImagesBucket.Arn

  # ArticleImagesBucketNotification:
  #   Type: AWS::S3::BucketNotification
  #   Properties:
  #     Bucket: !Ref ArticleImagesBucket
  #     NotificationConfiguration:
  #       LambdaFunctionConfigurations:
  #         - Event: s3:ObjectCreated:*
  #           Function: !GetAtt ThumbnailFunction.Arn
  #           Filter:
  #             S3Key:
  #               Rules:
  #                 - Name: prefix
  #                   Value: original/
  #   DependsOn: ThumbnailFunctionBucketEventPermission


  # ============================== STATIC SITE + CLOUDFRONT ==============================
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for Travel Guide

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

  ArticleImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArticleImagesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${ArticleImagesBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: StaticSite
            DomainName: !GetAtt StaticSiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
          - Id: Images
            DomainName: !GetAtt ArticleImagesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: StaticSite
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CacheBehaviors:
          - PathPattern: "articles/*"
            TargetOriginId: Images
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
          - PathPattern: "thumbnails/*"
            TargetOriginId: Images
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FrontendUrl:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  ImagesUrl:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}/articles/"