AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Guide Core Infrastructure - S3 Buckets, DynamoDB Tables, Cognito
Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues: [staging, prod]
    Description: Environment name
  CorsOrigin:
    Type: String
    Default: "*"
    Description: CORS origin for API Gateway
Conditions:
  IsProd: !Equals [!Ref Environment, prod]
Resources:
  ##############################
  # S3 BUCKETS
  ##############################
  ArticleImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub travel-guide-images-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: 
              - "GET"
              - "PUT"
              - "POST"
              - "DELETE"
              - "HEAD"
            AllowedOrigins: 
              - !Ref CorsOrigin
            AllowedHeaders: 
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub travel-guide-static-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  ##############################
  # DYNAMODB TABLES
  ##############################
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub articles-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: articleId
          AttributeType: S
        - AttributeName: visibility
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: gh5
          AttributeType: S
        - AttributeName: geohash
          AttributeType: S
      KeySchema:
        - AttributeName: articleId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_visibility_createdAt
          KeySchema:
            - AttributeName: visibility
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi_owner_createdAt
          KeySchema:
            - AttributeName: ownerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi_gh5_geohash
          KeySchema:
            - AttributeName: gh5
              KeyType: HASH
            - AttributeName: geohash
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  UserFavoritesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub user-favorites-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: articleId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: articleId
          KeyType: RANGE
  ##############################
  # COGNITO USER POOL
  ##############################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub TravelGuideUserPool-${Environment}
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub web-client-${Environment}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED
  ##############################
  # CLOUDFRONT
  ##############################
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for Travel Guide ${Environment}"
  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAIReadOnly
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"
  ArticleImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArticleImagesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAIReadImages
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${ArticleImagesBucket.Arn}/*"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3OriginStatic
            DomainName: !GetAtt StaticSiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
          - Id: S3OriginImages
            DomainName: !GetAtt ArticleImagesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3OriginStatic
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: 
            - "GET"
            - "HEAD"
          CachedMethods: 
            - "GET"
            - "HEAD"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        CacheBehaviors:
          - PathPattern: "articles/*"
            TargetOriginId: S3OriginImages
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: 
              - "GET"
              - "HEAD"
            CachedMethods: 
              - "GET"
              - "HEAD"
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
          - PathPattern: "thumbnails/*"
            TargetOriginId: S3OriginImages
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: 
              - "GET"
              - "HEAD"
            CachedMethods: 
              - "GET"
              - "HEAD"
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: TLSv1.2_2021
Outputs:
  # Article Service needs these outputs
  ArticlesTableArn:
    Value: !GetAtt ArticlesTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ArticlesTableArn"
  ArticlesTableName:
    Value: !Ref ArticlesTable
    Export:
      Name: !Sub "${AWS::StackName}-ArticlesTableName"
  ArticleImagesBucketName:
    Value: !Ref ArticleImagesBucket
    Export:
      Name: !Sub "${AWS::StackName}-ArticleImagesBucketName"
  ArticleImagesBucketArn:
    Value: !GetAtt ArticleImagesBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ArticleImagesBucketArn"
  UserFavoritesTableName:
    Value: !Ref UserFavoritesTable
    Export:
      Name: !Sub "${AWS::StackName}-UserFavoritesTableName"
  # Auth Service needs these outputs
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDomain"
  ImageProcessingDLQUrl:
    Value: !Ref ImageProcessingDLQ
    Export:
      Name: !Sub "${AWS::StackName}-ImageProcessingDLQUrl"